[2021-12-22 17:03:50,511] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: data_pipeline1.face_crop scheduled__2021-12-20T00:01:00+00:00 [queued]>
[2021-12-22 17:03:50,515] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: data_pipeline1.face_crop scheduled__2021-12-20T00:01:00+00:00 [queued]>
[2021-12-22 17:03:50,515] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-22 17:03:50,515] {taskinstance.py:1242} INFO - Starting attempt 2 of 4
[2021-12-22 17:03:50,516] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-22 17:03:50,525] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): face_crop> on 2021-12-20 00:01:00+00:00
[2021-12-22 17:03:50,528] {standard_task_runner.py:52} INFO - Started process 9512 to run task
[2021-12-22 17:03:50,532] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline1', 'face_crop', 'scheduled__2021-12-20T00:01:00+00:00', '--job-id', '21', '--raw', '--subdir', '/home/myamya/project/dockers/airflow/dags/hello_world.py', '--cfg-path', '/tmp/tmp4ugzv4um', '--error-file', '/tmp/tmp7xsrgr2f']
[2021-12-22 17:03:50,532] {standard_task_runner.py:77} INFO - Job 21: Subtask face_crop
[2021-12-22 17:03:50,550] {logging_mixin.py:109} INFO - Running <TaskInstance: data_pipeline1.face_crop scheduled__2021-12-20T00:01:00+00:00 [running]> on host myamya
[2021-12-22 17:03:50,566] {taskinstance.py:1412} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=yangjae
AIRFLOW_CTX_DAG_ID=data_pipeline1
AIRFLOW_CTX_TASK_ID=face_crop
AIRFLOW_CTX_EXECUTION_DATE=2021-12-20T00:01:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-20T00:01:00+00:00
[2021-12-22 17:03:50,566] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2021-12-22 17:03:50,566] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'docker run -it -v /home/myamya/project/image_files/:/home/myamya/project/image_files/ google_api:0.8 /bin/bash init.sh ']
[2021-12-22 17:03:50,570] {subprocess.py:85} INFO - Output:
[2021-12-22 17:03:51,404] {subprocess.py:89} INFO - 0
[2021-12-22 17:03:51,404] {subprocess.py:89} INFO - 2
[2021-12-22 17:03:51,404] {subprocess.py:89} INFO - 3
[2021-12-22 17:03:51,404] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/1.jpeg
[2021-12-22 17:03:52,445] {subprocess.py:89} INFO - [Info] /home/myamya/project/image_files/images/1.jpeg: Find face from in position [133, 48, 844, 875] and skew angle [-0.20883362, 0.14810006, -3.5433183]
[2021-12-22 17:03:52,823] {subprocess.py:89} INFO - [Info]  /home/myamya/project/image_files/images/1.jpeg: Crop face [133, 48, 844, 875] and write it to file : /home/myamya/project/image_files/cropped_image/1.jpeg
[2021-12-22 17:03:52,824] {subprocess.py:89} INFO - training 1
[2021-12-22 17:03:52,824] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/2259.jpeg
[2021-12-22 17:03:53,276] {subprocess.py:89} INFO - [Error] /home/myamya/project/image_files/images/2259.jpeg: cannot process file : 'y'
[2021-12-22 17:03:53,276] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/2260.jpeg
[2021-12-22 17:03:53,844] {subprocess.py:89} INFO - [Error] /home/myamya/project/image_files/images/2260.jpeg: cannot process file : 'y'
[2021-12-22 17:03:53,844] {subprocess.py:89} INFO - ## label 1 has 1 of training data
[2021-12-22 17:03:53,844] {subprocess.py:89} INFO - number of datas per label  [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[2021-12-22 17:03:54,141] {subprocess.py:93} INFO - Command exited with return code 0
[2021-12-22 17:03:54,158] {taskinstance.py:1270} INFO - Marking task as SUCCESS. dag_id=data_pipeline1, task_id=face_crop, execution_date=20211220T000100, start_date=20211222T080350, end_date=20211222T080354
[2021-12-22 17:03:54,197] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-22 17:03:54,222] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
