[2021-12-22 17:03:45,689] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: data_pipeline1.face_crop scheduled__2021-12-20T00:00:00+00:00 [queued]>
[2021-12-22 17:03:45,694] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: data_pipeline1.face_crop scheduled__2021-12-20T00:00:00+00:00 [queued]>
[2021-12-22 17:03:45,694] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-22 17:03:45,694] {taskinstance.py:1242} INFO - Starting attempt 2 of 4
[2021-12-22 17:03:45,694] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-22 17:03:45,703] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): face_crop> on 2021-12-20 00:00:00+00:00
[2021-12-22 17:03:45,706] {standard_task_runner.py:52} INFO - Started process 9403 to run task
[2021-12-22 17:03:45,711] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline1', 'face_crop', 'scheduled__2021-12-20T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', '/home/myamya/project/dockers/airflow/dags/hello_world.py', '--cfg-path', '/tmp/tmpjkm97152', '--error-file', '/tmp/tmpmb6tmy4w']
[2021-12-22 17:03:45,711] {standard_task_runner.py:77} INFO - Job 20: Subtask face_crop
[2021-12-22 17:03:45,737] {logging_mixin.py:109} INFO - Running <TaskInstance: data_pipeline1.face_crop scheduled__2021-12-20T00:00:00+00:00 [running]> on host myamya
[2021-12-22 17:03:45,774] {taskinstance.py:1412} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=yangjae
AIRFLOW_CTX_DAG_ID=data_pipeline1
AIRFLOW_CTX_TASK_ID=face_crop
AIRFLOW_CTX_EXECUTION_DATE=2021-12-20T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-20T00:00:00+00:00
[2021-12-22 17:03:45,775] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2021-12-22 17:03:45,775] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'docker run -it -v /home/myamya/project/image_files/:/home/myamya/project/image_files/ google_api:0.8 /bin/bash init.sh ']
[2021-12-22 17:03:45,781] {subprocess.py:85} INFO - Output:
[2021-12-22 17:03:46,587] {subprocess.py:89} INFO - 0
[2021-12-22 17:03:46,588] {subprocess.py:89} INFO - 2
[2021-12-22 17:03:46,588] {subprocess.py:89} INFO - 3
[2021-12-22 17:03:46,588] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/1.jpeg
[2021-12-22 17:03:47,683] {subprocess.py:89} INFO - [Info] /home/myamya/project/image_files/images/1.jpeg: Find face from in position [133, 48, 844, 875] and skew angle [-0.20883362, 0.14810006, -3.5433183]
[2021-12-22 17:03:48,063] {subprocess.py:89} INFO - [Info]  /home/myamya/project/image_files/images/1.jpeg: Crop face [133, 48, 844, 875] and write it to file : /home/myamya/project/image_files/cropped_image/1.jpeg
[2021-12-22 17:03:48,064] {subprocess.py:89} INFO - training 1
[2021-12-22 17:03:48,064] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/2259.jpeg
[2021-12-22 17:03:48,563] {subprocess.py:89} INFO - [Error] /home/myamya/project/image_files/images/2259.jpeg: cannot process file : 'y'
[2021-12-22 17:03:48,563] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/2260.jpeg
[2021-12-22 17:03:49,010] {subprocess.py:89} INFO - [Error] /home/myamya/project/image_files/images/2260.jpeg: cannot process file : 'y'
[2021-12-22 17:03:49,011] {subprocess.py:89} INFO - ## label 1 has 1 of training data
[2021-12-22 17:03:49,011] {subprocess.py:89} INFO - number of datas per label  [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[2021-12-22 17:03:49,307] {subprocess.py:93} INFO - Command exited with return code 0
[2021-12-22 17:03:49,324] {taskinstance.py:1270} INFO - Marking task as SUCCESS. dag_id=data_pipeline1, task_id=face_crop, execution_date=20211220T000000, start_date=20211222T080345, end_date=20211222T080349
[2021-12-22 17:03:49,375] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-22 17:03:49,423] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
