[2021-12-21 22:06:55,614] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: data_pipeline.face_crop scheduled__2021-12-19T00:04:00+00:00 [queued]>
[2021-12-21 22:06:55,617] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: data_pipeline.face_crop scheduled__2021-12-19T00:04:00+00:00 [queued]>
[2021-12-21 22:06:55,618] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-21 22:06:55,618] {taskinstance.py:1242} INFO - Starting attempt 1 of 4
[2021-12-21 22:06:55,618] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-21 22:06:55,626] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): face_crop> on 2021-12-19 00:04:00+00:00
[2021-12-21 22:06:55,628] {standard_task_runner.py:52} INFO - Started process 93551 to run task
[2021-12-21 22:06:55,629] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline', 'face_crop', 'scheduled__2021-12-19T00:04:00+00:00', '--job-id', '22', '--raw', '--subdir', '/home/myamya/project/dockers/airflow/dags/hello_world.py', '--cfg-path', '/tmp/tmps5omgyf1', '--error-file', '/tmp/tmpo_v1as52']
[2021-12-21 22:06:55,630] {standard_task_runner.py:77} INFO - Job 22: Subtask face_crop
[2021-12-21 22:06:55,647] {logging_mixin.py:109} INFO - Running <TaskInstance: data_pipeline.face_crop scheduled__2021-12-19T00:04:00+00:00 [running]> on host myamya
[2021-12-21 22:06:55,659] {taskinstance.py:1686} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/myamya/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/myamya/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1406, in _execute_task_with_callbacks
    self.render_templates(context=context)
  File "/home/myamya/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2088, in render_templates
    self.task.render_template_fields(context)
  File "/home/myamya/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1057, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/myamya/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1070, in _do_render_template_fields
    rendered_content = self.render_template(content, context, jinja_env, seen_oids)
  File "/home/myamya/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1105, in render_template
    return jinja_env.get_template(content).render(**context)
  File "/home/myamya/anaconda3/lib/python3.9/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/myamya/anaconda3/lib/python3.9/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/myamya/anaconda3/lib/python3.9/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/myamya/anaconda3/lib/python3.9/site-packages/jinja2/loaders.py", line 197, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: docker run -it -v /home/myamya/project/image_files/:/home/myamya/project/image_files/ google_api:0.8 /bin/bash init.sh
[2021-12-21 22:06:55,663] {taskinstance.py:1270} INFO - Marking task as UP_FOR_RETRY. dag_id=data_pipeline, task_id=face_crop, execution_date=20211219T000400, start_date=20211221T130655, end_date=20211221T130655
[2021-12-21 22:06:55,671] {standard_task_runner.py:88} ERROR - Failed to execute job 22 for task face_crop
Traceback (most recent call last):
  File "/home/myamya/anaconda3/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/myamya/anaconda3/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/myamya/anaconda3/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/myamya/anaconda3/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/myamya/anaconda3/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/myamya/anaconda3/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/home/myamya/anaconda3/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/myamya/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/myamya/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1406, in _execute_task_with_callbacks
    self.render_templates(context=context)
  File "/home/myamya/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2088, in render_templates
    self.task.render_template_fields(context)
  File "/home/myamya/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1057, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/myamya/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1070, in _do_render_template_fields
    rendered_content = self.render_template(content, context, jinja_env, seen_oids)
  File "/home/myamya/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1105, in render_template
    return jinja_env.get_template(content).render(**context)
  File "/home/myamya/anaconda3/lib/python3.9/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/myamya/anaconda3/lib/python3.9/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/myamya/anaconda3/lib/python3.9/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/myamya/anaconda3/lib/python3.9/site-packages/jinja2/loaders.py", line 197, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: docker run -it -v /home/myamya/project/image_files/:/home/myamya/project/image_files/ google_api:0.8 /bin/bash init.sh
[2021-12-21 22:06:55,681] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-12-21 22:06:55,692] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-12-21 23:21:16,279] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: data_pipeline.face_crop scheduled__2021-12-19T00:04:00+00:00 [queued]>
[2021-12-21 23:21:16,282] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: data_pipeline.face_crop scheduled__2021-12-19T00:04:00+00:00 [queued]>
[2021-12-21 23:21:16,282] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-21 23:21:16,282] {taskinstance.py:1242} INFO - Starting attempt 1 of 4
[2021-12-21 23:21:16,282] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-21 23:21:16,291] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): face_crop> on 2021-12-19 00:04:00+00:00
[2021-12-21 23:21:16,292] {standard_task_runner.py:52} INFO - Started process 108443 to run task
[2021-12-21 23:21:16,294] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline', 'face_crop', 'scheduled__2021-12-19T00:04:00+00:00', '--job-id', '157', '--raw', '--subdir', '/home/myamya/project/dockers/airflow/dags/hello_world.py', '--cfg-path', '/tmp/tmp0vrb9zpn', '--error-file', '/tmp/tmpqnr7f6p3']
[2021-12-21 23:21:16,295] {standard_task_runner.py:77} INFO - Job 157: Subtask face_crop
[2021-12-21 23:21:16,312] {logging_mixin.py:109} INFO - Running <TaskInstance: data_pipeline.face_crop scheduled__2021-12-19T00:04:00+00:00 [running]> on host myamya
[2021-12-21 23:21:16,345] {taskinstance.py:1412} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=yangjae
AIRFLOW_CTX_DAG_ID=data_pipeline
AIRFLOW_CTX_TASK_ID=face_crop
AIRFLOW_CTX_EXECUTION_DATE=2021-12-19T00:04:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-19T00:04:00+00:00
[2021-12-21 23:21:16,346] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2021-12-21 23:21:16,346] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'docker run -it -v /home/myamya/project/image_files/:/home/myamya/project/image_files/ google_api:0.8 /bin/bash init.sh ']
[2021-12-21 23:21:16,352] {subprocess.py:85} INFO - Output:
[2021-12-21 23:21:17,186] {subprocess.py:89} INFO - 0
[2021-12-21 23:21:17,186] {subprocess.py:89} INFO - 2
[2021-12-21 23:21:17,186] {subprocess.py:89} INFO - 3
[2021-12-21 23:21:17,186] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/1.jpeg
[2021-12-21 23:21:18,349] {subprocess.py:89} INFO - [Info] /home/myamya/project/image_files/images/1.jpeg: Find face from in position [133, 48, 844, 875] and skew angle [-0.20883362, 0.14810006, -3.5433183]
[2021-12-21 23:21:18,726] {subprocess.py:89} INFO - [Info]  /home/myamya/project/image_files/images/1.jpeg: Crop face [133, 48, 844, 875] and write it to file : /home/myamya/project/image_files/cropped_image/1.jpeg
[2021-12-21 23:21:18,727] {subprocess.py:89} INFO - training 1
[2021-12-21 23:21:18,727] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/2259.jpeg
[2021-12-21 23:21:19,194] {subprocess.py:89} INFO - [Error] /home/myamya/project/image_files/images/2259.jpeg: cannot process file : 'y'
[2021-12-21 23:21:19,194] {subprocess.py:89} INFO - ## label 1 has 1 of training data
[2021-12-21 23:21:19,194] {subprocess.py:89} INFO - number of datas per label  [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[2021-12-21 23:21:19,468] {subprocess.py:93} INFO - Command exited with return code 0
[2021-12-21 23:21:19,484] {taskinstance.py:1270} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=face_crop, execution_date=20211219T000400, start_date=20211221T142116, end_date=20211221T142119
[2021-12-21 23:21:19,517] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-21 23:21:19,536] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
